# Generated by Django 4.1 on 2022-08-09 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('plate', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='NavigationRecord',
            fields=[
                ('id', models.IntegerField(max_length=200, primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(verbose_name='date published')),
                ('latitude', models.FloatField(verbose_name='date published')),
                ('longitude', models.FloatField(verbose_name='date published')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evrekabackend.vehicle')),
            ],
        ),
    ]
