# Generated by Django 4.1 on 2022-08-09 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evrekabackend', '0002_alter_navigationrecord_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigationrecord',
            name='datetime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='navigationrecord',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='navigationrecord',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
